apiVersion: apps/v1
kind: Deployment
metadata:
  name: qupo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qupo-backend
  template:
    metadata:
      labels:
        app: qupo-backend
    spec:
      containers:
        - name: backend
          image: qupo/backend:latest
          ports:
            - containerPort: 8000
