apiVersion: apps/v1
kind: Deployment
metadata:
  name: qupo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qupo-frontend
  template:
    metadata:
      labels:
        app: qupo-frontend
    spec:
      containers:
        - name: frontend
          image: qupo/frontend:latest
          ports:
            - containerPort: 80
